# Generated by Django 5.0.4 on 2026-07-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('solusi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatDiagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('gejala_dipilih', models.ManyToManyField(to='diagnosa.gejala')),
                ('hasil_penyakit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosa.penyakit')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gejala', models.ManyToManyField(to='diagnosa.gejala')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='diagnosa.penyakit')),
            ],
        ),
    ]
