# Generated by Django 5.0.4 on 2026-07-20 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosa', '0002_pasien'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatdiagnosa',
            name='pasien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='diagnosa.pasien'),
            preserve_default=False,
        ),
    ]
