# Generated by Django 5.0.4 on 2026-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosa', '0003_riwayatdiagnosa_pasien'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='kode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
