# Generated by Django 5.0.4 on 2026-07-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosa', '0004_rule_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
