# Generated by Django 5.0.4 on 2026-07-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosa', '0005_pasien_alamat_pasien_tanggal_lahir'),
    ]

    operations = [
        migrations.CreateModel(
            name='GambarBeranda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Gambar Beranda', max_length=100)),
                ('gambar', models.ImageField(upload_to='beranda/')),
            ],
        ),
    ]
