# Generated by Django 5.0.4 on 2026-08-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosa', '0006_gambarberanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='gejala_or',
            field=models.ManyToManyField(blank=True, related_name='rule_or', to='diagnosa.gejala'),
        ),
    ]
