# Generated by Django 5.0.4 on 2026-08-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosa', '0007_rule_gejala_or'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
    ]
